---
title: Interactive timelines with timevis
author: Your Name
date: '2018-04-04'
slug: interactive-timelines-with-timevis
categories:
  - Administration
  - Coding
  - To-do
tags:
  - R
  - R packages
  - Rmarkdown
menu: "main"
---

An example timeline created with the R package [timevis](https://github.com/daattali/timevis).
```{r, echo=FALSE}
library(timevis)

data <- data.frame(
  id      = 1:11,
  content = c("Start", "", 
              "Research Proposal", "Obj 1. Phenotype Data QC & Analysis",
              "Obj 2. Gneotype Data QC & Annotation", "Obj 3. Heritability Analysis", 
              "Obj 4. Pedigree-based GWAS", "Obj 5. Machine-learning GWAS", "Finish", "", "Hand-in"),
  start   = c("2018-01-15", "2018-02-15", 
              "2018-02-15", "2018-03-29",
              "2018-05-01", "2018-05-28", 
              "2018-06-12", "2018-07-28", 
              "2018-11-01", "2018-03-29", "2018-10-07"),
  end     = c(NA, "2018-10-07", 
              "2018-03-28", "2018-05-07", 
              "2018-05-28", "2018-06-12", 
              "2018-07-28", "2018-09-20", 
              NA, "2018-09-20", NA),
  group   = c(3, rep(1, 2), rep(2, 5),3, 2, 3),
  type    = c("box", "background", "range", "range", "range", "range", "range", "range", "box", "background", "box"),
  style = c("color: black;", "color: cadetblue;", "color: cadetblue;", "color: darkred;",
            "color: darkred;", "color: darkred;", "color: darkred;", "color: darkred;", "color: black;", "color: darkred;", "color: black;"),
  options = list(editable = TRUE),
  fit = TRUE)

groups <- data.frame(id = c(1,2,3), content = c("Writing", "Analysis", "Admin"))
timevis(data, groups = groups, width = 1260, height = 250)
```

The code to generate the above timeline:
```{r, eval=FALSE}
library(timevis)

data <- data.frame(
  id      = 1:11,
  content = c("Start", "", 
              "Research Proposal", "Obj 1. Phenotype Data QC & Analysis",
              "Obj 2. Gneotype Data QC & Annotation", "Obj 3. Heritability Analysis", 
              "Obj 4. Pedigree-based GWAS", "Obj 5. Machine-learning GWAS", "Finish", "", "Hand-in"),
  start   = c("2018-01-15", "2018-02-15", 
              "2018-02-15", "2018-03-29",
              "2018-05-01", "2018-05-28", 
              "2018-06-12", "2018-07-28", 
              "2018-11-01", "2018-03-29", "2018-10-07"),
  end     = c(NA, "2018-10-07", 
              "2018-03-28", "2018-05-07", 
              "2018-05-28", "2018-06-12", 
              "2018-07-28", "2018-09-20", 
              NA, "2018-09-20", NA),
  group   = c(3, rep(1, 2), rep(2, 5),3, 2, 3),
  type    = c("box", "background", "range", "range", "range", "range", "range", "range", "box", "background", "box"),
  style = c("color: black;", "color: cadetblue;", "color: cadetblue;", "color: darkred;",
            "color: darkred;", "color: darkred;", "color: darkred;", "color: darkred;", "color: black;", "color: darkred;", "color: black;"),
  options = list(editable = TRUE),
  fit = TRUE)

groups <- data.frame(id = c(1,2,3), content = c("Writing", "Analysis", "Admin"))
timevis(data, groups = groups)
```
